apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:latest  # Tutaj używamy obrazu backendu, który zbudowałeś
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "db-service"  # nazwa usługi backendu MySQL
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "admin"
            - name: DB_NAME
              value: "index_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
