version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - db  # kontener web uruchomi się po db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: index_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db-data:

