version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: index_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db-data:
    driver: local
